### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by kazetrend** [manupsunny/PinLock#7]
Hey man.
I love this lib. Its very simple to use and easy to customize. 

The problem is when I tried to add 
compile 'com.manusunny:pinlock:+'
 the sync fails and the error messages says it couldnt find the file.

I only got it to work by putting in 

compile 'com.manusunny:pinlock:1.4.0'

based on the download tag. 
So i was wondering if this was the latest version.. If not, then what is it? 

I suggest maybe updating the readme for other users as well. 

Have an awesome day.
Cheers man.

**Comment by manupsunny** [comment]
Hi @kazetrend,

So sorry for the late reply. When we use '+' in build.gradle, we should enclose it within double quotes. So please try `compile "com.manusunny:pinlock:+"`

For more information, read [this comment](http://stackoverflow.com/questions/10370422/gradle-getting-the-latest-release-version-of-a-dependency#comment21033097_10373813) on stackoverflow.

**Comment by kazetrend** [comment]
@manupsunny 
Thanks for replying nonetheless. I shall remember this the next time I encounter something similar.
